Controllers/FeedController.cs
using System;
using System.IO;
using InstaDevFinal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InstaDevFinal.Controllers
{
    [Route("Feed")]
    public class FeedController : Controller
    {
        Post Postmodel = new Post();

        Usuario Usuariomodel = new Usuario();
        public IActionResult index()
        {
            ViewBag.Posts = Postmodel.LerTodosPost();
            ViewBag.Usuarios = Usuariomodel.LerTodosUsuarios();
            return View();
        }

        [Route("Postar")]
        public IActionResult Postar(IFormCollection form)
        {
            Post novopost = new Post();
            Random rdn = new Random();
            
            novopost.Id_post = rdn.Next(999999999).ToString();
            novopost.texto_post = form["texto_post"];
            novopost.Username = HttpContext.Session.GetString("Username");
            /* novopost.imagem = form["Imagem"]; */
             if (form.Files.Count > 0)
            {

                var file = form.Files[0];
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Posts");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                novopost.imagem = file.FileName;

            }
            else
            {
                novopost.imagem = "padrao.jpg";
            }

            Postmodel.PostarPost(novopost);
            ViewBag.Posts = Postmodel.LerTodosPost();

            return LocalRedirect("~/Feed");
        }

    }
}

Controllers/PerfilController.cs
using InstaDevFinal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InstaDevFinal.Controllers
{
    public class PerfilController : Controller
    {
        Usuario UsuarioModel = new Usuario();
        Post PostModel = new Post();

        public IActionResult Index()
        {
            ViewBag.User = HttpContext.Session.GetString("Username");
            ViewBag.PostPerfil = PostModel.PostPerfil(HttpContext.Session.GetString("Username").ToString());

            if (ViewBag.User != null)
            {
                return View();
            }

            return LocalRedirect("~/Home");
        }
        
        /* [Route("Perfil/Index")]
        public IActionResult Index()
        {
            ViewBag.Usuarios = Getstring;
            ViewBag.Posts = PostModel.LerTodosPost();
            /* return LocalRedirect("~/Perfil/Index"); 
            return View();
    } */

        [Route("Excluir/{Id_post}")]
    public IActionResult Excluir(int Id_post)
    {
        PostModel.Deletar(Id_post);
        ViewBag.Posts = PostModel.LerTodosPost();
        return LocalRedirect("~/Perfil/Index");
    }
}
}

Views/feed/Index.cshtml
@model Post
@{
    ViewData["Title"] = "Feed";
}

@foreach (var item in ViewBag.Usuarios)
{

    <div class="teste-aside">
        <section class="container container-aside">
            <div class="stories caixa-stories">
                <div class="caixa-arrumar">
                    <div class="pessoas-online">
                        <img src="~/img/@item.Foto" alt="">
                        <span>@item.Nome</span>
                    </div>
                </div>
                <section>
                    <div class="caixa-postar">
                        <div class="perfil-postar">
                            <img src="stories/gabigordo 1.png" alt="">
                            <span>Postar</span>
                        </div>

                        <div>
                            <form method="POST" action='@Url.Action("Postar")' enctype="multipart/form-data">
                                <input type="text" placeholder="Digite a descrição da imagem..." name="texto_post">
                                <label for="Imagem_post" class="escolher_foto">Escolha uma Imagem</label>
                                <input type="file" class="escolher-arquivo" id="Imagem_post" name="Imagem"> 
                                <button id="botao-postar">Postar</button>
                            </form>
                        </div>

                    </div>
                </section>
                @foreach (var coisa in ViewBag.Posts)
                {
                    <section>

                        <div class="caixa-post">
                            <div class="spanzinho">
                                <img class="perfil-post" src="stories/pele-perfil.png" alt="">
                                <div class="spanzao">
                                    <span id="ronaldinho"> @item.Username </span>
                                    <span>@coisa.texto_post </span>
                                </div>
                            </div>

                            <div>
                                <img class="post-do-perfil" src="~/img/Posts/@coisa.imagem" alt="">
                            </div>

                            <div class="caixa-comentar">
                                <img id="curtida" src="post/Vector.png" alt="">
                                <img id="comentar" src="post/Vector-1.png" alt="">
                                <div class="aba-comentar">
                                    <input type="text" placeholder="Comentar...">
                                    <hr>
                                </div>
                            </div>

                            <div id="curtidas">
                                <span id="numero-curtidas"> 5387 curtidas</span>
                            </div>

                            <div class="comentarios">
                                <div id="comentario">
                                    <span class="perfil-comentario">King_pele</span>
                                    <a href="">#R10</a>
                                    <p> Curvem - se perante o rei</p>
                                </div>

                                <div id="comentario">
                                    <span class="perfil-comentario">yes_baby</span>
                                    <p>nem te conheço, thank you</p>
                                </div>

                                <div id="comentario">
                                    <span class="perfil-comentario">Ronaldo</span>
                                    <p>Ja estou me curvando, meu rei</p>
                                </div>
                            </div>
                        </div>
                    </section>
                }

                <section>
                    <div class="caixa-post">
                        <div class="spanzinho">
                            <img class="perfil-post" src="stories/ronaldoinho gorducho.png" alt="">
                            <div class="spanzao">
                                <span id="ronaldinho"> RonaldoinhoFeiucho </span>
                                <span> Bar da esquina, SP</span>
                            </div>
                        </div>

                        <div>
                            <img class="post-do-perfil" src="post/Captura de tela 2021-06-25 113458.png" alt="">
                        </div>

                        <div class="caixa-comentar">
                            <img id="curtida" src="post/Vector.png" alt="">
                            <img id="comentar" src="post/Vector-1.png" alt="">
                            <div class="aba-comentar">
                                <input type="text" placeholder="Comentar...">
                                <hr>
                            </div>
                        </div>

                        <div id="curtidas">
                            <span id="numero-curtidas">777 curtidas</span>
                        </div>

                        <div class="comentarios">
                            <div id="comentario">
                                <span class="perfil-comentario">Gabigordo</span>
                                <a href="">#R10</a>
                                <p> O mais brabo de todos!!</p>
                            </div>

                            <div id="comentario">
                                <span class="perfil-comentario">Will_baiano</span>
                                <p>Eu lembro desse dia, vc tava em Bel-Air cmg</p>
                            </div>

                            <div id="comentario">
                                <span class="perfil-comentario">King_pele</span>
                                <p>Esse era pra ser meu sucessor, mas estragou a carreira no galo</p>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <div class="box-perfil">
                <div class="perfil-aside-chaves">
                    <img src="stories/chaves_metal 1.png" alt="">
                </div>
                <div class="nome-verds">
                    <a asp-area="" asp-controller="Perfil" asp-action="Index">chaves_metal</a>
                    <span id="nome-verdadeiro-perfil"> Chaves Bolaños</span>
                </div>
            </div>
        </section>
    </div>
}